package web.model;

import java.util.HashSet;
import java.util.Set;

/**
 * Stormenu generated by MyEclipse Persistence Tools
 */

public class Menu implements java.io.Serializable,Comparable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer menuId;

	private String menuName;

	private String mparentId;

	private String menuLevel;

	private String menuUrl;

	private String menuDesc;
	private Set <Role>storroles;
	// Constructors


	/** default constructor */
	public Menu() {
	}

	/** full constructor */
	public Menu(String menuName, String mparentId, String menuLevel,
			String menuUrl, String menuDesc) {
		this.menuName = menuName;
		this.mparentId = mparentId;
		this.menuLevel = menuLevel;
		this.menuUrl = menuUrl;
		this.menuDesc = menuDesc;
	}
	public int compareTo(Object object) {
        //物件本身与o1相比较，如果retrun正值，就表示比o1大
		Menu plimit = (Menu) object;		
        if( Integer.parseInt(this.getMenuLevel()) > Integer.parseInt(plimit.getMenuLevel()) ){
            return 1;
        }else{
            return -1;
        }
	}
	// Property accessors

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMparentId() {
		return this.mparentId;
	}

	public void setMparentId(String mparentId) {
		this.mparentId = mparentId;
	}

	public String getMenuLevel() {
		return this.menuLevel;
	}

	public void setMenuLevel(String menuLevel) {
		this.menuLevel = menuLevel;
	}

	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	public String getMenuDesc() {
		return this.menuDesc;
	}

	public void setMenuDesc(String menuDesc) {
		this.menuDesc = menuDesc;
	}

	public Set<Role> getStorroles() {
		return storroles;
	}

	public void setStorroles(Set<Role> storroles) {
		this.storroles = storroles;
	}

	public Menu(Integer menuId, String menuName, String mparentId, String menuLevel, String menuUrl, String menuDesc, Set<Role> storroles) {
		super();
		this.menuId = menuId;
		this.menuName = menuName;
		this.mparentId = mparentId;
		this.menuLevel = menuLevel;
		this.menuUrl = menuUrl;
		this.menuDesc = menuDesc;
		this.storroles = storroles;
	}
}