package web.model;

/**
 * Roletomenu generated by MyEclipse Persistence Tools
 */

public class Roletomenu implements java.io.Serializable {

	// Fields

	private static final long serialVersionUID = 1L;

	private Integer rtomid;

	private Integer roleid;

	private Integer menuid;

	// Constructors

	/** default constructor */
	public Roletomenu() {
	}

	/** full constructor */
	public Roletomenu(Integer roleid, Integer menuid) {
		this.roleid = roleid;
		this.menuid = menuid;
	}

	// Property accessors

	public Integer getRtomid() {
		return this.rtomid;
	}

	public void setRtomid(Integer rtomid) {
		this.rtomid = rtomid;
	}

	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	public Integer getMenuid() {
		return this.menuid;
	}

	public void setMenuid(Integer menuid) {
		this.menuid = menuid;
	}

}